# Use the official Eclipse Mosquitto image as the base
FROM eclipse-mosquitto:latest

# Set the maintainer label
LABEL maintainer="Alina Klishyna <alinakotova102@gmail.com>"

# Copy custom configuration file
COPY mosquitto.conf /mosquitto/config/mosquitto.conf